//jdbc.driverClassName.driver = org.mariadb.jdbc.Driver
//jdbc.driverClassName.driver = com.mysql.cj.jdbc.Driver
jdbc.driverClassName.driver=org.h2.Driver
//jdbc.url = jdbc:mysql://localhost:3306/financial_db
jdbc.url=jdbc:h2:mem:tesetdb
jdbc.username = dhuskey
jdbc.password = password
hibernate.dialect = org.hibernate.dialect.MySQLDialect
//hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.show_sql = true
hibernate.format_sql = true
hibernate.hbm2ddl.auto = create-drop